//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Customers
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryArea
    {
        public int DeliveryAreaID { get; set; }
        public string DeliveryArea1 { get; set; }
        public Nullable<bool> DeliveryAvailable { get; set; }
        public Nullable<double> DeliveryCharges { get; set; }
        public Nullable<int> ApproxDeliveryTime { get; set; }
    }
}
