//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_screens
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ItemID { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> UnitPrice { get; set; }
        public Nullable<int> UnitsinStick { get; set; }
        public Nullable<bool> Availability { get; set; }
        public Nullable<int> VendorID { get; set; }
    }
}
